"""
seed_server.py — run ON THE SERVER to push UUIDs to the local API without SSL.

Reads uuids.txt (one UUID per line, generated by: python push_uuids.py --dry-run > uuids.txt)
and POSTs them to http://localhost:8000/api/admin/discover in batches.

Usage (on server):
    python3 seed_server.py
    python3 seed_server.py --uuids uuids.txt --batch 100
"""

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error


def read_env(path=".env"):
    env = {}
    try:
        for line in open(path):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    except FileNotFoundError:
        pass
    return env


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--uuids", default="uuids.txt", help="UUID list file (one per line)")
    parser.add_argument("--batch", default=100, type=int, help="UUIDs per request")
    args = parser.parse_args()

    if not os.path.exists(args.uuids):
        sys.exit(f"UUID file not found: {args.uuids}\nGenerate it with: python push_uuids.py --dry-run > uuids.txt")

    raw = open(args.uuids, "rb").read()
    text = raw.decode("utf-16") if raw[:2] in (b"\xff\xfe", b"\xfe\xff") else raw.decode("utf-8-sig")
    uuids = [u.strip() for u in text.splitlines() if u.strip()]
    print(f"Loaded {len(uuids)} UUIDs from {args.uuids}")

    env = read_env()
    token = env.get("DASHBOARD_PASSWORD", "")

    batches = [uuids[i:i + args.batch] for i in range(0, len(uuids), args.batch)]
    total_new = 0
    total_dup = 0

    for i, batch in enumerate(batches, 1):
        print(f"Batch {i}/{len(batches)} ({len(batch)} UUIDs)...", end=" ", flush=True)
        data = json.dumps({"uuids": batch}).encode()
        req = urllib.request.Request(
            "http://localhost:8000/api/admin/discover",
            data=data,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {token}",
            },
        )
        try:
            resp = urllib.request.urlopen(req, timeout=30)
            result = json.loads(resp.read())
            new = result.get("new_count", 0)
            dup = result.get("duplicate_count", 0)
            total_new += new
            total_dup += dup
            print(f"OK — {new} new, {dup} already known")
        except urllib.error.HTTPError as e:
            print(f"FAILED — HTTP {e.code} {e.read().decode()[:120]}")
        except Exception as e:
            print(f"FAILED — {e}")
        if i < len(batches):
            time.sleep(1)

    print(f"\nDone. {total_new} new UUIDs queued for discovery, {total_dup} duplicates skipped.")
    if total_new:
        print("discover.py is running in the background — check: docker compose logs api -f")


if __name__ == "__main__":
    main()
